name: Hackable

on:
  workflow_run:
    workflows: [Vulnerable workflow]
    types:
      - completed

jobs:
  job1:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclution == 'success'
    steps:
      - name: blabla
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: artifact
      - name: save data
        id: artifact
        run: echo "::set-output name=id::$(<artifact.txt)"
      - name: using
        id: deploy
        run: |
          echo ${{ steps.artifact.output.id }}
