name: Vulnerable workflow
on: pull_request

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: echo "; echo 'ofek was here'; " > artifact.txt
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./artifact.txt
